/* =========================================================
   PERSONAL DASHBOARD — STAGE 5
   Search and advanced task filtering
========================================================= */

const STORAGE_KEYS={tasks:"dashboardTasks",notes:"dashboardNotes",filter:"dashboardTaskFilter"};
const taskForm=document.getElementById("taskForm"),taskInput=document.getElementById("taskInput"),taskPriority=document.getElementById("taskPriority"),taskDueDate=document.getElementById("taskDueDate"),taskList=document.getElementById("taskList"),emptyState=document.getElementById("emptyState"),emptyStateTitle=document.getElementById("emptyStateTitle"),emptyStateMessage=document.getElementById("emptyStateMessage");
const totalTasksElement=document.getElementById("totalTasks"),activeTasksElement=document.getElementById("activeTasks"),completedTasksElement=document.getElementById("completedTasks"),allCount=document.getElementById("allCount"),allTasksCount=document.getElementById("allTasksCount"),activeCount=document.getElementById("activeCount"),completedCount=document.getElementById("completedCount"),taskCountBadge=document.getElementById("taskCountBadge");
const currentDateElement=document.getElementById("currentDate"),currentYearElement=document.getElementById("currentYear"),progressBar=document.getElementById("progressBar"),progressCircle=document.getElementById("progressCircle"),progressCirclePercentage=document.getElementById("progressCirclePercentage"),progressPercentage=document.getElementById("progressPercentage"),progressMessage=document.getElementById("progressMessage"),progressTrack=document.querySelector(".progress-track");
const clearCompletedButton=document.getElementById("clearCompleted"),filterButtons=document.querySelectorAll(".filter-button"),navLinks=document.querySelectorAll(".sidebar-link"),sidebar=document.getElementById("sidebar"),sidebarOverlay=document.querySelector(".sidebar-overlay"),menuButton=document.querySelector(".menu-button"),sidebarClose=document.querySelector(".sidebar-close"),focusTaskButton=document.getElementById("focusTaskButton"),notesInput=document.getElementById("notesInput"),savedIndicator=document.getElementById("savedIndicator"),exportDataButton=document.getElementById("exportDataButton"),resetDataButton=document.getElementById("resetDataButton"),upcomingList=document.getElementById("upcomingList");

let tasks=loadTasks(),currentFilter=loadFilter(),editingTaskId=null,notesSaveTimer,searchTerm="",priorityFilter="all",dueFilter="all";

function createId(){return crypto?.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`}
function normalizePriority(v){return ["low","medium","high"].includes(v)?v:"medium"}
function normalizeDueDate(v){return typeof v==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(v)?v:""}
function loadTasks(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEYS.tasks)||"[]");return Array.isArray(p)?p.filter(t=>t&&typeof t.text==="string").map(t=>({id:t.id??createId(),text:t.text.trim().slice(0,200),completed:Boolean(t.completed),priority:normalizePriority(t.priority),dueDate:normalizeDueDate(t.dueDate),createdAt:t.createdAt||new Date().toISOString(),updatedAt:t.updatedAt||t.createdAt||new Date().toISOString()})).filter(t=>t.text):[]}catch(e){console.error(e);return[]}}
function saveTasks(){try{localStorage.setItem(STORAGE_KEYS.tasks,JSON.stringify(tasks));return true}catch(e){showToast("Could not save your tasks.","error");return false}}
function loadFilter(){try{const v=localStorage.getItem(STORAGE_KEYS.filter);return ["all","active","completed"].includes(v)?v:"all"}catch{return"all"}}
function saveFilter(){try{localStorage.setItem(STORAGE_KEYS.filter,currentFilter)}catch(e){console.error(e)}}
function loadNotes(){if(!notesInput)return;try{notesInput.value=localStorage.getItem(STORAGE_KEYS.notes)||""}catch(e){console.error(e)}}
function saveNotes(){if(!notesInput)return;try{localStorage.setItem(STORAGE_KEYS.notes,notesInput.value);if(savedIndicator){savedIndicator.textContent="Saved";clearTimeout(notesSaveTimer);notesSaveTimer=setTimeout(()=>savedIndicator.textContent="Ready",1200)}}catch(e){if(savedIndicator)savedIndicator.textContent="Not saved"}}
function isOverdue(t){return !t.completed&&!!t.dueDate&&t.dueDate<new Date().toISOString().slice(0,10)}
function formatDueDate(v){if(!v)return"";const d=new Date(`${v}T00:00:00`);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(d)}
function priorityLabel(v){return v.charAt(0).toUpperCase()+v.slice(1)}
function createTask(text,priority,dueDate){const clean=text.trim().slice(0,200);if(!clean)return false;const now=new Date().toISOString();tasks.push({id:createId(),text:clean,completed:false,priority:normalizePriority(priority),dueDate:normalizeDueDate(dueDate),createdAt:now,updatedAt:now});saveTasks();currentFilter="all";saveFilter();renderTasks();showToast("Task added.");return true}
function updateTask(id,text,priority,dueDate){const clean=text.trim().slice(0,200);if(!clean)return false;let found=false;tasks=tasks.map(t=>String(t.id)!==String(id)?t:(found=true,{...t,text:clean,priority:normalizePriority(priority),dueDate:normalizeDueDate(dueDate),updatedAt:new Date().toISOString()}));if(!found)return false;saveTasks();showToast("Task updated.");return true}
function startEditingTask(id){if(tasks.some(t=>String(t.id)===String(id))){editingTaskId=String(id);renderTasks()}}
function cancelEditingTask(){editingTaskId=null;renderTasks()}
function finishEditingTask(id,text,priority,date){if(!updateTask(id,text,priority,date)){showToast("Task text cannot be empty.","error");return}editingTaskId=null;renderTasks()}
function deleteTask(id){const exists=tasks.some(t=>String(t.id)===String(id));tasks=tasks.filter(t=>String(t.id)!==String(id));if(editingTaskId===String(id))editingTaskId=null;saveTasks();renderTasks();if(exists)showToast("Task deleted.")}
function toggleTask(id){let done=false;tasks=tasks.map(t=>String(t.id)!==String(id)?t:(done=!t.completed,{...t,completed:done,updatedAt:new Date().toISOString()}));saveTasks();renderTasks();showToast(done?"Task completed.":"Task marked active.")}
function clearCompletedTasks(){const n=tasks.filter(t=>t.completed).length;if(!n)return showToast("There are no completed tasks to clear.");tasks=tasks.filter(t=>!t.completed);editingTaskId=null;saveTasks();renderTasks();showToast(`${n} completed ${n===1?"task":"tasks"} cleared.`)}
function matchesAdvancedFilters(t){const q=searchTerm.trim().toLowerCase();if(q&&!t.text.toLowerCase().includes(q))return false;if(priorityFilter!=="all"&&t.priority!==priorityFilter)return false;if(dueFilter==="overdue"&&!isOverdue(t))return false;if(dueFilter==="scheduled"&&!t.dueDate)return false;if(dueFilter==="today"&&t.dueDate!==new Date().toISOString().slice(0,10))return false;return true}
function sortTasks(list){return[...list].sort((a,b)=>Number(isOverdue(b))-Number(isOverdue(a))||(!a.dueDate?1:!b.dueDate?-1:a.dueDate.localeCompare(b.dueDate))||String(b.createdAt).localeCompare(String(a.createdAt)))}
function getFilteredTasks(){let list=currentFilter==="active"?tasks.filter(t=>!t.completed):currentFilter==="completed"?tasks.filter(t=>t.completed):tasks;return sortTasks(list.filter(matchesAdvancedFilters))}
function updateCounts(){const total=tasks.length,completed=tasks.filter(t=>t.completed).length,active=total-completed;[[totalTasksElement,total],[activeTasksElement,active],[completedTasksElement,completed],[allCount,total],[allTasksCount,total],[activeCount,active],[completedCount,completed],[taskCountBadge,total]].forEach(([e,v])=>{if(e)e.textContent=v})}
function updateProgress(){const total=tasks.length,done=tasks.filter(t=>t.completed).length,p=total?Math.round(done/total*100):0;if(progressBar)progressBar.style.width=`${p}%`;if(progressPercentage)progressPercentage.textContent=`${p}%`;if(progressCirclePercentage)progressCirclePercentage.textContent=`${p}%`;if(progressCircle)progressCircle.style.setProperty("--progress",`${p}%`);if(progressTrack)progressTrack.setAttribute("aria-valuenow",p);if(progressMessage)progressMessage.textContent=!total?"Start by adding your first task.":p===100?"Everything is complete. Great work! 🎉":p<50?"Good start. Keep making progress.":"You're making great progress. Keep going."}
function updateEmptyState(list){if(!emptyState)return;emptyState.hidden=list.length>0;if(list.length)return;if(!tasks.length){emptyStateTitle.textContent="No tasks yet";emptyStateMessage.textContent="Add your first task to get started."}else if(searchTerm||priorityFilter!=="all"||dueFilter!=="all"){emptyStateTitle.textContent="No matching tasks";emptyStateMessage.textContent="Try changing your search or filters."}else if(currentFilter==="active"){emptyStateTitle.textContent="No active tasks";emptyStateMessage.textContent="You've completed everything. Nice work!"}else{emptyStateTitle.textContent="No completed tasks";emptyStateMessage.textContent="Completed tasks will appear here."}}
function createMeta(t){const meta=document.createElement("div");meta.className="task-meta";const p=document.createElement("span");p.className=`priority-badge ${t.priority}`;p.textContent=`${priorityLabel(t.priority)} priority`;meta.append(p);if(t.dueDate){const d=document.createElement("span");d.className=`due-date${isOverdue(t)?" overdue":""}`;d.textContent=isOverdue(t)?`Overdue · ${formatDueDate(t.dueDate)}`:`Due · ${formatDueDate(t.dueDate)}`;meta.append(d)}return meta}
function createTaskElement(t){const article=document.createElement("article");article.className=`task-item${t.completed?" completed":""}${isOverdue(t)?" overdue":""}`;const check=document.createElement("input");check.type="checkbox";check.className="task-checkbox";check.checked=t.completed;check.setAttribute("aria-label",`${t.completed?"Mark active":"Mark completed"}: ${t.text}`);check.addEventListener("change",()=>toggleTask(t.id));const content=document.createElement("div");content.className="task-content";const actions=document.createElement("div");actions.className="task-actions";
if(editingTaskId===String(t.id)){const input=document.createElement("input");input.type="text";input.className="task-edit-input";input.value=t.text;input.maxLength=200;const select=document.createElement("select");select.className="task-edit-select";["low","medium","high"].forEach(v=>select.add(new Option(`${priorityLabel(v)} priority`,v)));select.value=t.priority;const date=document.createElement("input");date.type="date";date.className="task-edit-date";date.value=t.dueDate;const editActions=document.createElement("div");editActions.className="task-edit-actions";const save=document.createElement("button");save.type="button";save.className="edit-save";save.textContent="Save";save.addEventListener("click",()=>finishEditingTask(t.id,input.value,select.value,date.value));const cancel=document.createElement("button");cancel.type="button";cancel.className="edit-cancel";cancel.textContent="Cancel";cancel.addEventListener("click",cancelEditingTask);editActions.append(save,cancel);content.append(input,select,date,editActions);input.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();finishEditingTask(t.id,input.value,select.value,date.value)}else if(e.key==="Escape")cancelEditingTask()});requestAnimationFrame(()=>{input.focus();input.select()})}else{const text=document.createElement("span");text.className="task-text";text.textContent=t.text;content.append(text,createMeta(t));const edit=document.createElement("button");edit.type="button";edit.className="edit-button";edit.textContent="Edit";edit.addEventListener("click",()=>startEditingTask(t.id));actions.append(edit)}
const del=document.createElement("button");del.type="button";del.className="delete-task";del.textContent="×";del.setAttribute("aria-label",`Delete task: ${t.text}`);del.addEventListener("click",()=>deleteTask(t.id));actions.append(del);article.append(check,content,actions);return article}
function renderUpcoming(){if(!upcomingList)return;const list=tasks.filter(t=>!t.completed&&t.dueDate).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,4);upcomingList.replaceChildren();if(!list.length){const e=document.createElement("div");e.className="upcoming-empty";e.innerHTML='<div class="upcoming-icon">📅</div><div><strong>Nothing scheduled</strong><p>Tasks with due dates will appear here.</p></div>';upcomingList.append(e);return}list.forEach(t=>{const item=document.createElement("div");item.className=`upcoming-item${isOverdue(t)?" overdue":""}`;const title=document.createElement("strong");title.textContent=t.text;const date=document.createElement("span");date.textContent=isOverdue(t)?`Overdue · ${formatDueDate(t.dueDate)}`:formatDueDate(t.dueDate);item.append(title,date);upcomingList.append(item)})}
function updateFilterButtons(){filterButtons.forEach(b=>{const active=b.dataset.filter===currentFilter;b.classList.toggle("active",active);b.setAttribute("aria-pressed",String(active))})}
function updateSearchUI(){const status=document.getElementById("taskFilterStatus");if(status){const visible=getFilteredTasks().length;const advanced=searchTerm||priorityFilter!=="all"||dueFilter!=="all";status.textContent=advanced?`${visible} matching ${visible===1?"task":"tasks"}: ${[searchTerm?`“${searchTerm}”`:"",priorityFilter!=="all"?`${priorityLabel(priorityFilter)} priority`:"",dueFilter!=="all"?dueFilter:""].filter(Boolean).join(" · ")}`:"Showing all tasks"}}
function renderTasks(){if(!taskList)return;taskList.replaceChildren();const list=getFilteredTasks();list.forEach(t=>taskList.append(createTaskElement(t)));updateEmptyState(list);updateCounts();updateProgress();renderUpcoming();updateSearchUI()}
function setActiveFilter(f){if(!["all","active","completed"].includes(f))return;editingTaskId=null;currentFilter=f;saveFilter();updateFilterButtons();renderTasks()}
function resetAdvancedFilters(){searchTerm="";priorityFilter="all";dueFilter="all";const s=document.getElementById("taskSearch"),p=document.getElementById("priorityFilter"),d=document.getElementById("dueFilter");if(s)s.value="";if(p)p.value="all";if(d)d.value="all";renderTasks()}
function setupAdvancedFilters(){const toolbar=document.querySelector(".task-toolbar");if(!toolbar||document.getElementById("taskSearch"))return;const panel=document.createElement("div");panel.className="advanced-task-filters";panel.style.cssText="display:grid;grid-template-columns:minmax(180px,1fr) auto auto auto;gap:.5rem;margin:.75rem 0 1rem";panel.innerHTML='<input id="taskSearch" type="search" placeholder="Search tasks..." aria-label="Search tasks"><select id="priorityFilter" aria-label="Filter by priority"><option value="all">All priorities</option><option value="high">High priority</option><option value="medium">Medium priority</option><option value="low">Low priority</option></select><select id="dueFilter" aria-label="Filter by due date"><option value="all">All due dates</option><option value="today">Due today</option><option value="scheduled">Scheduled</option><option value="overdue">Overdue</option></select><button id="clearAdvancedFilters" type="button" class="small-button">Clear</button>';toolbar.after(panel);const status=document.createElement("div");status.id="taskFilterStatus";status.style.cssText="margin:-.5rem 0 1rem;color:var(--text-muted);font-size:.72rem";panel.after(status);const search=document.getElementById("taskSearch"),priority=document.getElementById("priorityFilter"),due=document.getElementById("dueFilter");search.addEventListener("input",()=>{searchTerm=search.value;renderTasks()});priority.addEventListener("change",()=>{priorityFilter=priority.value;renderTasks()});due.addEventListener("change",()=>{dueFilter=due.value;renderTasks()});document.getElementById("clearAdvancedFilters").addEventListener("click",resetAdvancedFilters)}
function openSidebar(){sidebar?.classList.add("open");sidebarOverlay?.classList.add("visible");document.body.classList.add("menu-open");menuButton?.setAttribute("aria-expanded","true");sidebarClose?.focus()}
function closeSidebar(){sidebar?.classList.remove("open");sidebarOverlay?.classList.remove("visible");document.body.classList.remove("menu-open");menuButton?.setAttribute("aria-expanded","false")}
function showToast(message,type="success"){let toast=document.getElementById("dashboardToast");if(!toast){toast=document.createElement("div");toast.id="dashboardToast";toast.setAttribute("role","status");toast.setAttribute("aria-live","polite");Object.assign(toast.style,{position:"fixed",right:"20px",bottom:"20px",zIndex:"9999",maxWidth:"min(360px,calc(100vw - 40px))",padding:"12px 16px",borderRadius:"10px",color:"#fff",fontSize:"14px",fontWeight:"700",boxShadow:"0 12px 30px rgba(15,23,42,.18)",opacity:"0",transform:"translateY(8px)",transition:"opacity .2s,transform .2s"});document.body.append(toast)}toast.textContent=message;toast.style.background=type==="error"?"#dc2626":"#0f172a";requestAnimationFrame(()=>{toast.style.opacity="1";toast.style.transform="translateY(0)"});clearTimeout(toast._timer);toast._timer=setTimeout(()=>{toast.style.opacity="0";toast.style.transform="translateY(8px)"},2200)}
function exportData(){const data={tasks,notes:notesInput?.value||"",filter:currentFilter,exportedAt:new Date().toISOString(),version:"5.0"};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`personal-dashboard-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url);showToast("Dashboard data exported.")}
function resetData(){if(!confirm("Reset all dashboard tasks and notes? This cannot be undone."))return;try{Object.values(STORAGE_KEYS).forEach(k=>localStorage.removeItem(k))}catch(e){console.error(e)}tasks=[];currentFilter="all";editingTaskId=null;if(notesInput)notesInput.value="";resetAdvancedFilters();updateFilterButtons();renderTasks();showToast("Dashboard data reset.")}

taskForm?.addEventListener("submit",e=>{e.preventDefault();if(createTask(taskInput?.value||"",taskPriority?.value||"medium",taskDueDate?.value||"")){taskForm.reset();if(taskPriority)taskPriority.value="medium";taskInput?.focus()}});
filterButtons.forEach(b=>b.addEventListener("click",()=>setActiveFilter(b.dataset.filter)));clearCompletedButton?.addEventListener("click",clearCompletedTasks);notesInput?.addEventListener("input",saveNotes);exportDataButton?.addEventListener("click",exportData);resetDataButton?.addEventListener("click",resetData);focusTaskButton?.addEventListener("click",()=>taskInput?.scrollIntoView({behavior:"smooth",block:"center"}));menuButton?.addEventListener("click",openSidebar);sidebarClose?.addEventListener("click",closeSidebar);sidebarOverlay?.addEventListener("click",closeSidebar);navLinks.forEach(l=>l.addEventListener("click",closeSidebar));document.addEventListener("keydown",e=>{if(e.key==="Escape")closeSidebar()});
if(currentDateElement)currentDateElement.textContent=new Intl.DateTimeFormat("en-US",{weekday:"long",year:"numeric",month:"long",day:"numeric"}).format(new Date());if(currentYearElement)currentYearElement.textContent=new Date().getFullYear();loadNotes();updateFilterButtons();setupAdvancedFilters();renderTasks();